* http://www.arjanwrites.com/arjanwrites/2008/02/listen-to-zazie.html
My favorite song on the album is the epic and gorgeous pop-rock tune "Je Suis Un
Homme," which translates to "I Am Human." (I'm glad my six years of studying
French still comes in handy sometimes.) The track is a very explicit statement
about the state of world. Zazie sings about overpopulation, famine, the lack of
proper drinking water and the ignorance of the "consumerist" Western world.
Famed director Yvan Attal directed a fitting video to visualize that message.

the word "homme" literally means man in French but is used here to mean man as
in a human being, humanity, a person, etc.

I am a man and I realize the horror of my nature, as a sentance, a punishment,
(Me) I turn round, I turn round.
* wpen
Written and composed by Zazie, alongside Philippe Paradis and Jean-Pierre Pilot,
the song deals in a critical and pessimistic way about the human behavior
towards the environmental issues and the consumer society.[1] On 17 April 2007,
Zazie herself announced in the media that "Je suis un homme would be the second
single off the Totem album.[2] The music video was directed by Yvan Attal[3] and
the shooting was made at the Mac / Val, the Musée d'art contemporain of
Vitry-sur-Seine. It shows the singer as a naked pregnant woman at an exhibition
about the humanity. The woman is worried about various problems presented,
including population explosion, forest devastated, deaths by malnutrition, CO2
emissions...[4] The song, as well as the music video, are available on Zazie's
greatest hits compilation Zest of.
* wpfr
Zazie expose un point de vue pessimiste sur la nature de l'Homme et son attitude
envers l'Environnement. Elle y fait également une critique de la société de
consommation (« Pur produit de consommation »), de la nature égoïste de l'Homme
(« je suis un homme au cœur de lion , « je fais le monde à ma façon ») et de
l'intolérance dont il peut faire preuve (« À la guerre en toute saison »). Tout
ceci aboutit à d'inévitables conséquences qu'elle expose également (« c'est moi
le maitre du monde et vois ce que j'en ai fait, une terre glacée, une terre
brûlée, la Terre des hommes que les hommes abandonnent »). La vidéo officielle
montre la chanteuse comme étant une femme qui semble consternée par la
déforestation, la pollution, la surpopulation, etc.
* http://www.songmeanings.net/songs/view/3530822107858717950/
Well, it's the pondering of the artist upon Man being materialistic and having
done nothing worthwhile except destroying the world in which he lives.

